# Generated by Django 3.0.8 on 2020-07-19 01:50

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.IntegerField()),
                ('name', models.CharField(max_length=10)),
                ('primary_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('secondary_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('city', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=10)),
                ('field_or_industry', models.CharField(max_length=50)),
                ('school_or_company', models.CharField(max_length=50)),
                ('degree_or_job', models.CharField(max_length=50)),
                ('other_info', models.TextField()),
            ],
            options={
                'ordering': ['student_number'],
            },
        ),
    ]
