# Generated by Django 3.0.8 on 2020-07-19 01:52

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='other_info',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='secondary_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
