# Generated by Django 3.0.8 on 2020-07-19 05:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contacts', '0003_auto_20200719_0155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='id',
        ),
        migrations.AlterField(
            model_name='contact',
            name='student_number',
            field=models.IntegerField(primary_key=True, serialize=False,
                                      validators=[django.core.validators.MinValueValidator(20160201),
                                                  django.core.validators.MaxValueValidator(20160242)]),
        ),
    ]
