# Generated by Django 3.0.8 on 2020-07-19 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
        ('contacts', '0004_auto_20200719_0500'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                       to='users.User'),
        ),
    ]
