# Generated by Django 3.0.8 on 2020-07-19 18:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacts', '0005_contact_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                       to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contact',
            name='student_number',
            field=models.IntegerField(primary_key=True, serialize=False,
                                      validators=[django.core.validators.MinValueValidator(20160200),
                                                  django.core.validators.MaxValueValidator(20160242)]),
        ),
    ]
